'use strict';
const assert = require('node:assert/strict');
const { chart } = require('../js/ef-chart.js');
const history = values => values.map((ef,i) => ({iso: '2026-08-' + String(i+1).padStart(2,'0'), ef}));
const flat = chart(history([1,1,1,1]));
assert.equal(flat.extent,10);
assert.ok(flat.points.every(p => p.y===88));
assert.equal(flat.change,0);
const wobble = chart(history([1,1.003,.999,1.002]));
assert.equal(wobble.extent,10);
assert.ok(Math.max(...wobble.points.map(p=>p.y))-Math.min(...wobble.points.map(p=>p.y)) < 3);
const rising = chart(history([1,1.02,1.04,1.06]));
assert.ok(Math.abs(rising.change-6)<1e-9);
assert.ok(rising.points[3].y<rising.points[0].y);
const falling = chart(history([1,.98,.96,.94]));
assert.ok(Math.abs(falling.change+6)<1e-9);
const large = chart(history([1,1.4,.7]));
assert.equal(large.extent,45);
assert.ok(large.points.every(p=>p.y>18&&p.y<158));
const rolling = chart(history(Array.from({length:20},(_,i)=>1+i*.001)));
assert.equal(rolling.points.length,12);
assert.equal(rolling.reference.iso,'2026-08-01');
assert.ok(rolling.points[0].pct>.79);
assert.equal(chart(history([1])),null);
assert.equal(chart(history([NaN,0,-1,Infinity,1])),null);
const irregular = chart([{iso:'2026-08-11',ef:1.1},{iso:'2026-08-01',ef:1},{iso:'2026-08-02',ef:1.01}]);
assert.ok(Math.abs(irregular.points[1].x-75.8)<1e-9);
assert.equal(irregular.reference.iso,'2026-08-01');
assert.ok(Math.abs(irregular.change-10)<1e-9);
assert.equal(flat.width,340);
assert.equal(flat.height,194);
console.log('EF chart: flat, wobble, rising, falling, scale expansion, rolling reference, invalid data and elapsed dates passed');
