'use strict';
const assert=require('node:assert/strict');
const {summarize}=require('../js/run-progress.js');
const a={iso:'2026-09-01',km:5,sec:1800},b={iso:'2026-09-03',km:5,sec:1700};
let s=summarize([a,b], '2026-09-10');
assert.equal(s.km,10);assert.equal(s.runs,2);assert.equal(s.weeks,1);
assert.equal(s.bests[0].iso,b.iso);assert.equal(s.bests[0].compared,2);
assert.equal(summarize([a], '2026-09-10').bests.length,0);
assert.equal(summarize([a], '2026-09-10').longest,null);
assert.equal(summarize([a,{...b,sec:1800}], '2026-09-10').bests[0].iso,a.iso);
s=summarize([a,b,{iso:'2026-09-08',km:10,sec:3000},{iso:'2026-09-09',km:4.999,sec:1200}], '2026-09-10');
assert.equal(s.bests.length,1);assert.equal(s.bests[0].km,5);
assert.equal(s.longest.km,10);assert.equal(s.weeks,2);
assert.equal(s.km,24.999); // No fabricated 5 km split from the 10 km run.
assert.equal(summarize([a,b],a.iso).runs,1);
assert.equal(summarize([a,{...a,sec:1600}], '2026-09-10').runs,1);
assert.equal(summarize([{...a,km:NaN},{...b,sec:-1}], '2026-09-10').runs,0);
assert.deepEqual(summarize([], '2026-09-10').bests,[]);
console.log('Run progress: exact-distance bests, ties, single logs, totals, weeks, future/invalid logs and duplicates passed');

const {debrief}=require('../js/run-progress.js');
const first={iso:'2026-09-01',km:10,sec:3900,cls:'race',hr:145};
const second={iso:'2026-09-08',km:10,sec:3750,cls:'race',hr:143};
const third={iso:'2026-09-15',km:10,sec:3600,cls:'race',hr:141};
// Easy runs are never ranked by time (rule 1): no best, even when quicker.
assert.equal(debrief([{...first,cls:'easy'},{...second,cls:'easy'},{...third,cls:'easy'}],third.iso,'2026-09-30').best,null);
assert.equal(summarize([{...first,cls:'easy'},{...third,cls:'easy'}],'2026-09-30').bests.length,0);
assert.equal(summarize([first,third],'2026-09-30').bests.length,1);
let report=debrief([third,first,second,{...third,iso:'2026-09-20',sec:3500}],third.iso,'2026-09-30');
assert.equal(report.best.previous.iso,second.iso);
assert.equal(report.best.gainSec,150);
assert.equal(report.best.count,3);
assert.equal(report.runCount,3);
assert.equal(report.totalKm,30);
assert.equal(report.deltaPaceSec,15);
assert.equal(report.deltaHr,-2);
assert.equal(report.longest,null);
assert.equal(debrief([first],first.iso,third.iso).best,null);
assert.equal(debrief([first],first.iso,third.iso).longest,null);
assert.equal(debrief([first,second,{...third,sec:3750}],third.iso,third.iso).best,null);
assert.equal(debrief([first,{...second,km:9.999}],second.iso,third.iso).best,null);
assert.equal(debrief([first,{...second,estimatedKm:true}],second.iso,third.iso).best,null);
assert.equal(debrief([{...first,estimatedKm:true},second],second.iso,third.iso).best,null);
assert.equal(summarize([{...first,estimatedKm:true},second],third.iso).bests.length,0);
assert.equal(summarize([{...first,estimatedKm:true},second],third.iso).longest,null);
report=debrief([first,{...second,km:12,sec:4300,cls:'long'}],second.iso,third.iso);
assert.equal(report.longest.gainKm,2);
assert.equal(report.previous,null);
assert.equal(report.deltaPaceSec,null);
assert.equal(debrief([first,{...second,hr:null}],second.iso,third.iso).deltaHr,null);
assert.equal(debrief([first,{...second,cls:'unclassified'}],second.iso,third.iso).previous,null);
report=debrief([{...first,km:90,estimatedKm:true},second],second.iso,third.iso);
assert.equal(report.milestone,100);
assert.equal(report.estimatedCount,1);
assert.equal(report.totalKm,100);
assert.equal(debrief([{...first,km:89.99},second],second.iso,third.iso).milestone,null);
assert.equal(debrief([{...first,km:100},second],second.iso,third.iso).milestone,null);
assert.equal(debrief([{...first,km:90},{...second,km:220}],second.iso,third.iso).milestone,300);
assert.equal(debrief([first,second,{...second,sec:3700}],second.iso,third.iso).current.sec,3700);
report=debrief([null,{...first,iso:'2026-02-30'},{...first,km:NaN},{...first,sec:-1},second],second.iso,third.iso);
assert.equal(report.runCount,1);
assert.equal(debrief([first,second],second.iso,first.iso),null);
assert.equal(debrief([first],'2026-02-30',third.iso),null);
assert.equal(debrief([first],second.iso,third.iso),null);
const frozen=Object.freeze([Object.freeze({...first}),Object.freeze({...second})]);
assert.equal(debrief(frozen,second.iso,third.iso).totalKm,20);
console.log('Run debrief: historical records, exact distances, ties, estimates, neutral comparisons, milestones, edits and invalid/future logs passed');
