'use strict';
const assert = require('assert/strict');
const S = require('../js/run-stream');
const origin = Date.parse('2026-09-16T12:00:00Z');
const points = [];
for (let i=0;i<=114;i++) points.push({time:origin+i*10000,distance:i<=60?i*2000/60:2000+(i-60)*2000/54,hr:i<60?140:160});
const r = S.summarize([points],'TCX');
assert.equal(r.values.km,4); assert.equal(r.values.sec,1140);
assert.equal(r.values.hr,149);
assert.deepEqual(r.stream.hrSeconds,[[140,600],[160,540]]);
assert.ok(Math.abs(r.stream.splitSec+60)<1e-8);
assert.ok(Math.abs(r.stream.decPct-(1-(2000*60/(160*540))/(2000*60/(140*600)))*100)<1e-8);
assert.equal(r.stream.coveredSec,1140);
const missing=points.map((p,i)=>({...p,hr:i===5?null:p.hr}));
const partial=S.summarize([missing],'TCX');
assert.equal(partial.values.hr,null); assert.equal(partial.stream.coveredSec,1130); assert.equal(partial.stream.decPct,null);
const gap=points.map((p,i)=>({...p,time:p.time+(i>=10?60000:0)}));
assert.equal(S.summarize([gap],'TCX').stream.decPct,null);
assert.equal(S.summarize([points.slice(0,61),points.slice(60)],'TCX').stream.splitSec,null);
const reset=points.map((p,i)=>({...p,distance:i>=60?p.distance-2000:p.distance}));
assert.equal(S.summarize([reset],'TCX').stream.decPct,null);
assert.throws(()=>S.summarize([[{time:0,distance:0},{time:1000,distance:500}]],'TCX'),/No usable/);
assert.equal(S.metres({lat:null,lon:0},{lat:0,lon:0}),null);
assert.ok(Math.abs(S.metres({lat:0,lon:0},{lat:0,lon:.001})-111.1949)<.01);
console.log('Run stream: time weighting, equal-distance halves, missing HR, gaps, resets, segments and GPS distance passed');
