'use strict';
const assert = require('assert/strict');
const fs = require('fs');
const vm = require('vm');
const source = fs.readFileSync(require.resolve('../js/app.js'), 'utf8');
const helper = name => source.match(new RegExp('  function ' + name + '\\([^]*?\\n  \\}'))[0];
const context = { fmtShort: iso => iso, fmtLeft: vm.runInNewContext('(' + helper('fmtLeft') + ')') };
const focusWindow = vm.runInNewContext('(' + helper('focusWindow') + ')', context);
const block = { startMin: 600, endMin: 660 };
assert.equal(focusWindow(block, '2026-09-19', '2026-09-19', 590), 'Starts in 10 min');
assert.equal(focusWindow(block, '2026-09-19', '2026-09-19', 600), '1h 00m left in scheduled window');
assert.equal(focusWindow(block, '2026-09-19', '2026-09-19', 659), '1 min left in scheduled window');
assert.equal(focusWindow(block, '2026-09-19', '2026-09-19', 660), 'Scheduled window ended');
assert.equal(focusWindow(block, '2026-09-19', '2026-09-20', 10), 'Scheduled window ended');
assert.equal(focusWindow(block, '2026-09-20', '2026-09-19', 650), 'Scheduled for 2026-09-20');
console.log('Session focus: scheduled window boundaries, future preview and midnight rollover passed');
const brief = vm.runInNewContext('(' + helper('focusBrief') + ')');
const text = 'First instruction · WHEN TIRED: use the reduced dose. Extra rationale · ordinary explanation';
assert.equal(brief(text).intro, 'First instruction');
assert.equal(brief(text).rules[0], 'WHEN TIRED: use the reduced dose');
assert.equal(brief('Warm up first · ordinary explanation').rules.length, 0);
const DB = require('../js/day-builder');
const monday = DB.buildDay('2026-09-14').blocks.find(b => b.cat === 'gym');
const rules = brief(monday.detail).rules.join(' ');
assert.match(rules, /AFTER A BRUTAL SUNDAY.*halve it/);
assert.match(rules, /SHARP OR ONE-SIDED PAIN.*skip the lower-body work entirely, upper only/);
