'use strict';
const assert=require('assert/strict');
const DB=require('../js/day-builder');
const empty=DB.trainingJourney(()=>({}),()=>null,'2026-09-19');
assert.equal(empty.weeks.length,30);
assert.equal(empty.elapsedWeeks,11);
assert.equal(empty.recorded,0);
assert.equal(empty.activeWeeks,0);
const monday=DB.buildDay('2026-09-14'), tuesday=DB.buildDay('2026-09-15');
const logs={'2026-09-14':{km:4.5,sec:1800},'2026-09-15':{km:8.25,sec:3000},'2026-09-20':{km:999,sec:3000}};
const j=DB.trainingJourney(iso=>iso==='2026-09-15'?{[tuesday.run.id]:true}:{},iso=>logs[iso],'2026-09-19');
assert.equal(monday.run,null);
assert.equal(j.recorded,12.75);assert.equal(j.runs,2);assert.equal(j.activeWeeks,1);
assert.equal(j.weeks[11].days[0].recorded,4.5);
assert.equal(j.weeks[11].days[6].recorded,0,'future logs excluded');
const legacy=DB.trainingJourney(iso=>iso==='2026-09-15'?{[tuesday.run.id]:true}:{},()=>null,'2026-09-19');
assert.equal(legacy.recorded,tuesday.run.run.km);assert.equal(legacy.weeks[11].days[1].estimated,true);
for(const w of j.weeks) assert.equal(w.planned,w.days.reduce((n,d)=>n+d.planned,0));
assert.ok(j.weeks[29].planned>42.2,'race week includes race and preceding runs');
assert.equal(j.weeks[29].longest,42.2);
assert.equal(DB.trainingJourney(()=>({}),()=>null,'2026-01-01').elapsedWeeks,0);
assert.equal(DB.trainingJourney(()=>({}),()=>null,'2027-02-01').elapsedWeeks,30);
console.log('Training journey: resolved special weeks, actual logs, ticks, unplanned runs, no double counting, future exclusion and calendar boundaries passed');
